#!/usr/bin/env python3
import argparse
import glob
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="tensorflow.lite.python.convert")

"""
CYD Network Sniffer — Multi-task TFLite Model Training

Reads feature CSVs and labels.csv, trains a multi-task neural network
(anomaly detection, packet classification, protocol ID, device
fingerprinting, routing decision), and exports a quantized int8 TFLite
model + C headers for deployment.

Usage:
    python training/train_model.py --data_dir training/data --output_dir training/output --model <model_type> --balance <feature_cols>

The data_dir should contain:
    - feat_*.csv files from the sniffer
    - labels.csv (generated by generate_labels.py, then reviewed)
"""

# ── Feature columns (must match ESP32 feature_extractor output) ── #

FEATURE_COLS = [
    "pkt_count", "avg_pkt_size", "std_pkt_size", "avg_rssi",
    "pkt_rate", "mgmt_ratio", "data_ratio", "ctrl_ratio",
    "unique_dst_count", "beacon_rate", "probe_req_rate", "retry_ratio",
]

# ── Label definitions ── #

ANOMALY_CLASSES = ["normal", "anomalous"]

PACKET_CLASSES = ["normal", "suspicious", "malicious", "unknown"]

PROTOCOL_CLASSES = [
    "wifi_mgmt", "wifi_data", "wifi_ctrl",
    "dhcp", "dns", "http", "https", "mqtt", "unknown",
]

DEVICE_CLASSES = [
    "router", "phone", "laptop", "iot_sensor", "smart_home",
    "camera", "printer", "game_console", "unknown",
]

ROUTE_ACTIONS = ["allow", "throttle", "block"]

RNN_LAYERS = {
    "lstm_lr": tf.keras.layers.LSTM,
    "gru_lr": tf.keras.layers.GRU,
    "rnn_lr": tf.keras.layers.SimpleRNN,
}

OUTPUT_NAMES = [
    "anomaly", "packet_class", "protocol", "device_type", "route_action",
]

LABEL_CLASSES = {
    "anomaly": ANOMALY_CLASSES,
    "packet_class": PACKET_CLASSES,
    "protocol": PROTOCOL_CLASSES,
    "device_type": DEVICE_CLASSES,
    "route_action": ROUTE_ACTIONS,
}


def prepare_flat_data(features, labels):
    """Merge, encode, scale, and split data for flat models."""
    print("Merging data...")
    df = merge_data(features, labels)

    print("Encoding labels...")
    df, _ = encode_labels(df)

    X = df[FEATURE_COLS].values.astype(np.float32)
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    enc_cols = [n + "_enc" for n in OUTPUT_NAMES]
    y_all = [df[c].values for c in enc_cols]

    # unique_macs = df["src_mac"].unique()
    # train_macs, test_macs = train_test_split(unique_macs, test_size=0.2, random_state=42)
    # train_mask = df["src_mac"].isin(train_macs)
    # train_idx = np.where(train_mask)[0]
    # test_idx = np.where(~train_mask)[0]
    indices = np.arange(len(X))
    train_idx, test_idx = train_test_split(indices, test_size=0.2, random_state=42, stratify=y_all[1])

    X_train, X_test = X[train_idx], X[test_idx]
    y_train = [v[train_idx] for v in y_all]
    y_test = [v[test_idx] for v in y_all]

    print(f"\nTrain: {len(X_train)}, Test: {len(X_test)}")
    print(f"Features: {len(FEATURE_COLS)}")

    return X_train, y_train, X_test, y_test, scaler

def load_features(data_dir: str) -> pd.DataFrame:
    pattern = os.path.join(data_dir, "feat_*.csv")
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No feature files found matching {pattern}")

    dfs = []
    for f in files:
        df = pd.read_csv(f)
        dfs.append(df)
        print(f"  Loaded {f}: {len(df)} rows")

    combined = pd.concat(dfs, ignore_index=True)
    print(f"Total feature rows: {len(combined)}")
    return combined


def load_labels(data_dir: str) -> pd.DataFrame:
    path = os.path.join(data_dir, "labels.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Labels file not found: {path}\n"
            f"Run generate_labels.py first to create it."
        )
    return pd.read_csv(path)


def merge_data(features: pd.DataFrame, labels: pd.DataFrame) -> pd.DataFrame:
    merged = features.merge(labels, on="src_mac", how="inner")
    print(f"Merged rows (labeled): {len(merged)}")
    if len(merged) == 0:
        raise ValueError(
            "No matching MACs between features and labels. "
            "Check that labels.csv src_mac values match the captured data."
        )
    return merged


def build_model(n_features: int):

    inputs = tf.keras.Input(shape=(n_features,), name="features")

    x = tf.keras.layers.Dense(64, activation="relu")(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    x = tf.keras.layers.Dense(32, activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    shared = tf.keras.layers.Dropout(0.2)(x)

    outputs = _build_output_heads(shared)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return _compile_model(model)


def encode_labels(df: pd.DataFrame):
    encoders = {}
    for name in OUTPUT_NAMES:
        class_list = LABEL_CLASSES[name]
        mapping = {label: idx for idx, label in enumerate(class_list)}
        df[name + "_enc"] = df[name].map(mapping)
        # Flag any labels not in the fixed class list
        unmapped = df[name + "_enc"].isna().sum()
        if unmapped > 0:
            print(f"  WARNING: {unmapped} rows in '{name}' have unknown labels, defaulting to last class")
            df[name + "_enc"] = df[name + "_enc"].fillna(len(class_list) - 1)
        df[name + "_enc"] = df[name + "_enc"].astype(int)
        encoders[name] = mapping
    return df, encoders

def evaluate_model(model, X_test, y_test, model_name):
    """Run model.evaluate + per-head classification reports."""
    print(f"\n{'='*60}")
    print(f"\n  {model_name} Evaluation ")
    print(f"\n{'='*60}\n")
    results = model.evaluate(X_test, y_test, verbose=0)
    for name, val in zip(model.metrics_names, results):
        print(f"  {name}: {val:.4f}")

    y_preds = model.predict(X_test, verbose=0)
    for i, name in enumerate(OUTPUT_NAMES):
        y_pred_classes = np.argmax(y_preds[i], axis=1)
        classes_present = np.unique(np.concatenate([y_test[i], y_pred_classes]))
        target_names = [LABEL_CLASSES[name][int(c)] for c in classes_present]

        print(f"\n--- {name} ---")
        print(classification_report(
            y_test[i], y_pred_classes,
            labels=classes_present,
            target_names=target_names,
            zero_division=0,
        ))
    print(f"\n{'='*60}\n")

def compute_sample_weights(y_train_list, balance_heads):
    combined = np.ones(len(y_train_list[0]), dtype=np.float32)

    for i, name in enumerate(OUTPUT_NAMES):
        if name not in balance_heads:
            continue
        classes = np.unique(y_train_list[i])
        weights = compute_class_weight("balanced", classes=classes, y=y_train_list[i])
        weight_dict = dict(zip(classes, weights))
        head_weights = np.array([weight_dict[v] for v in y_train_list[i]], dtype=np.float32)
        combined *= head_weights

    combined /= combined.mean()
    return combined

def compute_per_head_weights(y_train_list, balance_heads):
    """Compute separate sample weights for each output head."""
    all_weights = []
    for i, name in enumerate(OUTPUT_NAMES):
        if name not in balance_heads:
            all_weights.append(np.ones(len(y_train_list[i]), dtype=np.float32))
            continue
        classes = np.unique(y_train_list[i])
        weights = compute_class_weight("balanced", classes=classes, y=y_train_list[i])
        weight_dict = dict(zip(classes, weights))
        head_weights = np.array([weight_dict[v] for v in y_train_list[i]], dtype=np.float32)
        head_weights /= head_weights.mean()
        all_weights.append(head_weights)
    return all_weights

def prepare_balance_weights(y_train, args):
    """Compute sample weights with route_action excluded."""
    balance_heads = set(args.balance) if args.balance is not None else set(OUTPUT_NAMES)
    balance_heads.discard("route_action")
    print(f"  Balancing: {sorted(balance_heads)}")
    return compute_per_head_weights(y_train, balance_heads)

def fit_model(model, X_train, y_train, X_test, y_test, sample_weights, args):
    """Fit with standard callbacks, return history."""
    # sw_list = [sample_weights for _ in OUTPUT_NAMES]
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss", patience=15, restore_best_weights=True
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6
        ),
    ]
    return model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=args.epochs,
        batch_size=args.batch_size,
        sample_weight=sample_weights,
        callbacks=callbacks,
        verbose=1,
    )

def convert_to_tflite(model, scaler, X_train, args):

    def representative_dataset():
        for i in range(min(200, len(X_train))):
            yield [X_train[i:i+1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter._experimental_calibrate_only = False
    converter.experimental_new_quantizer = True
    tflite_model = converter.convert()

    tflite_path = os.path.join(args.output_dir, "sniffer_model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)
    print(f"\nTFLite model saved: {tflite_path} ({len(tflite_model)} bytes)")

    header_path = os.path.join(args.output_dir, "sniffer_model.h")
    with open(header_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write(f"// Auto-generated — {len(tflite_model)} bytes\n")
        f.write(f"alignas(16) const unsigned char sniffer_model[] = {{\n")
        for i, byte in enumerate(tflite_model):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x}, ")
            if i % 12 == 11:
                f.write("\n")
        f.write(f"\n}};\n")
        f.write(f"const unsigned int sniffer_model_len = {len(tflite_model)};\n")
    print(f"C header saved: {header_path}")

    scaler_path = os.path.join(args.output_dir, "scaler_params.h")
    with open(scaler_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write(f"// StandardScaler parameters — {len(FEATURE_COLS)} features\n")
        f.write(f"const float SCALER_MEAN[] = {{\n    ")
        f.write(", ".join(f"{v:.6f}f" for v in scaler.mean_))
        f.write("\n};\n\n")
        f.write(f"const float SCALER_SCALE[] = {{\n    ")
        f.write(", ".join(f"{v:.6f}f" for v in scaler.scale_))
        f.write("\n};\n")
    print(f"Scaler params saved: {scaler_path}")

    mapping_path = os.path.join(args.output_dir, "label_mappings.h")
    with open(mapping_path, "w") as f:
        f.write("#pragma once\n\n")
        tasks = [
            ("ANOMALY", ANOMALY_CLASSES),
            ("PACKET_CLASS", PACKET_CLASSES),
            ("PROTOCOL", PROTOCOL_CLASSES),
            ("DEVICE_TYPE", DEVICE_CLASSES),
            ("ROUTE_ACTION", ROUTE_ACTIONS),
        ]
        for task, classes in tasks:
            f.write(f"const char* {task}_LABELS[] = {{\n")
            for cls in classes:
                f.write(f'    "{cls}",\n')
            f.write("};\n")
            f.write(f"static const int {task}_COUNT = {len(classes)};\n\n")
    print(f"Label mappings saved: {mapping_path}")

    print("\nDone! Copy these files to sniffer/src/ for deployment:")
    print(f"  {args.output_dir}/sniffer_model.h")
    print(f"  {args.output_dir}/scaler_params.h")
    print(f"  {args.output_dir}/label_mappings.h")
    print()


#--- Models --- #

def train_nn(X_train, y_train, X_test, y_test, scaler, args):
    # Class balancing
    sample_weights = prepare_balance_weights(y_train, args)
    # Build Model
    model = build_model(len(FEATURE_COLS))
    model.summary()
    print()
    # Train 
    fit_model(model, X_train, y_train, X_test, y_test, sample_weights, args)
    # Evaluate Model Performance 
    evaluate_model(model, X_test, y_test, "Dense NN")
    # Export Model
    convert_to_tflite(model, scaler, X_train, args)


def train_rf(X_train, y_train, X_test, y_test, args):

    balance_heads = set(args.balance) if args.balance is not None else set(OUTPUT_NAMES)

    print(f"\n{'='*60}")
    print("Random Forest Baseline — one classifier per output head")
    print(f"{'='*60}")

    for i, name in enumerate(OUTPUT_NAMES):
        class_weight = "balanced" if name in balance_heads else None
        rf = RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            class_weight=class_weight,
            random_state=42,
            n_jobs=-1,
        )
        rf.fit(X_train, y_train[i])

        y_pred = rf.predict(X_test[i] if isinstance(X_test, list) else X_test)
        acc = accuracy_score(y_test[i], y_pred)

        classes_present = np.unique(np.concatenate([y_test[i], y_pred]))
        class_names = LABEL_CLASSES[name]
        target_names = [class_names[int(c)] for c in classes_present]

        print(f"\n--- {name} (accuracy: {acc:.4f}, balanced: {class_weight is not None}) ---")
        print(classification_report(
            y_test[i], y_pred,
            labels=classes_present,
            target_names=target_names,
            zero_division=0,
        ))

        importances = rf.feature_importances_
        ranked = sorted(zip(FEATURE_COLS, importances), key=lambda x: -x[1])
        print(f"  Top features: ", end="")
        print(", ".join(f"{name}={imp:.3f}" for name, imp in ranked[:5]))



def assemble_windows(data_dir: str, window_size: int):
    """Build sliding time-series windows from all feature rows.

    Every row in every feat_N.csv is treated as one timestep.  Files are
    processed in sorted order so rows from feat_2 come before feat_4, etc.
    For each src_mac we concatenate all its rows chronologically, then
    extract stride-1 sliding windows of ``window_size`` consecutive steps.
    Short sequences are zero-padded on the left.

    Returns
    -------
    windows : dict[str, np.ndarray]
        mac -> (n_windows, window_size, n_features)
    file_order : list[str]
        Ordered list of feature files used.
    """
    pattern = os.path.join(data_dir, "feat_*.csv")
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No feature files matching {pattern}")

    print(f"  Found {len(files)} feature files for windowing")

    # Collect ALL rows per MAC across files in chronological order
    mac_series: dict = {}
    total_rows = 0
    for fpath in files:
        df = pd.read_csv(fpath)
        for mac, group in df.groupby("src_mac"):
            rows = group[FEATURE_COLS].values.astype(np.float32)
            if mac not in mac_series:
                mac_series[mac] = []
            mac_series[mac].append(rows)
            total_rows += len(rows)

    print(f"  Total rows across all MACs: {total_rows}")

    n_features = len(FEATURE_COLS)
    windows: dict = {}

    for mac, row_blocks in mac_series.items():
        # Concatenate all rows for this MAC in file order
        seq = np.concatenate(row_blocks, axis=0)  # (T, n_features)
        T = len(seq)

        if T < window_size:
            pad = np.zeros((window_size - T, n_features), dtype=np.float32)
            seq = np.concatenate([pad, seq], axis=0)
            T = window_size

        n_win = T - window_size + 1
        wins = np.array([seq[i:i + window_size] for i in range(n_win)],
                        dtype=np.float32)
        windows[mac] = wins

    total_wins = sum(w.shape[0] for w in windows.values())
    print(f"  Assembled {total_wins} windows across {len(windows)} MACs "
          f"(window_size={window_size}, stride=1)")
    return windows, files

def _build_output_heads(shared):
    """Attach 5 Dense+softmax (logistic-regression) output heads."""
    anomaly_out = tf.keras.layers.Dense(
        len(ANOMALY_CLASSES), activation="softmax", name="anomaly"
    )(shared)
    packet_out = tf.keras.layers.Dense(
        len(PACKET_CLASSES), activation="softmax", name="packet_class"
    )(shared)
    protocol_out = tf.keras.layers.Dense(
        len(PROTOCOL_CLASSES), activation="softmax", name="protocol"
    )(shared)
    device_out = tf.keras.layers.Dense(
        len(DEVICE_CLASSES), activation="softmax", name="device_type"
    )(shared)
    route_out = tf.keras.layers.Dense(
        len(ROUTE_ACTIONS), activation="softmax", name="route_action"
    )(shared)
    return [anomaly_out, packet_out, protocol_out, device_out, route_out]


def _compile_model(model):
    """Shared compile configuration for hybrid models."""
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss={
            "anomaly": "sparse_categorical_crossentropy",
            "packet_class": "sparse_categorical_crossentropy",
            "protocol": "sparse_categorical_crossentropy",
            "device_type": "sparse_categorical_crossentropy",
            "route_action": "sparse_categorical_crossentropy",
        },
        metrics={
            "anomaly": ["accuracy"],
            "packet_class": ["accuracy"],
            "protocol": ["accuracy"],
            "device_type": ["accuracy"],
            "route_action": ["accuracy"],
        },
    )
    return model


def build_hybrid_lr(arch: str, window_size: int, n_features: int):
    """Build RNN temporal encoder -> Dense+softmax (LR) heads."""
    layer_cls = RNN_LAYERS[arch]
    inputs = tf.keras.Input(shape=(window_size, n_features), name="sequence")
    x = layer_cls(64, return_sequences=False, unroll=True)(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    shared = tf.keras.layers.Dropout(0.3)(x)
    outputs = _build_output_heads(shared)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return _compile_model(model)


def train_hybrid(features, labels, args):
    """Train a hybrid RNN+LR model using time-series windows.
    Hybrid models (LSTM_LR, GRU_LR, RNN_LR)combine deep sequence models with 
    classical classifiers: Temporal feature extraction via 
    RNN backbone + Dense+softmax (logistic regression) output heads.
    """

    model_name = args.model.upper().replace("_", " -> ")
    print(f"\n{'='*60}")
    print(f"Hybrid model: {model_name}")
    print(f"Window size:  {args.window_size}")
    print(f"{'='*60}")

    # 1) Assemble windows
    print("\nAssembling time-series windows...")
    windows, _ = assemble_windows(args.data_dir, args.window_size)

    # 2) Encode labels (one label per MAC — broadcast to all windows)
    labels_df = labels.copy()
    labels_df, encoders = encode_labels(labels_df)

    enc_cols = [n + "_enc" for n in OUTPUT_NAMES]

    X_list = []
    y_lists = [[] for _ in OUTPUT_NAMES]

    for _, row in labels_df.iterrows():
        mac = row["src_mac"]
        if mac not in windows:
            continue
        wins = windows[mac]
        X_list.append(wins)
        for j, col in enumerate(enc_cols):
            y_lists[j].extend([row[col]] * len(wins))

    if not X_list:
        raise ValueError(
            "No labeled MACs found in windowed data. "
            "Check that labels.csv MACs match feat_*.csv MACs."
        )

    X_all = np.concatenate(X_list, axis=0)
    y_all = [np.array(y, dtype=np.int32) for y in y_lists]

    print(f"  Total windows: {len(X_all)}")
    print(f"  Shape: {X_all.shape}")

    # 3) Scale features (per-timestep, same scaler logic as flat model)
    scaler = StandardScaler()
    orig_shape = X_all.shape
    X_flat = X_all.reshape(-1, X_all.shape[-1])
    X_flat = scaler.fit_transform(X_flat)
    X_all = X_flat.reshape(orig_shape).astype(np.float32)

    # 4) Train/test split
    # mac_labels = labels_df.set_index("src_mac")["anomaly"]
    # # unique_macs = labels_df["src_mac"].unique()
    # unique_macs = mac_labels.index.values
    # strat_key = mac_labels.values
    # train_macs, test_macs = train_test_split(unique_macs, test_size=0.2, random_state=42, stratify=strat_key)
    # train_mask = labels_df["src_mac"].isin(train_macs)
    # train_idx = np.where(train_mask)[0]
    # test_idx = np.where(~train_mask)[0]
    indices = np.arange(len(X_all))
    train_idx, test_idx = train_test_split(indices, test_size=0.2, random_state=42, stratify=y_all[1])

    X_train, X_test = X_all[train_idx], X_all[test_idx]
    y_train = [y[train_idx] for y in y_all]
    y_test = [y[test_idx] for y in y_all]

    print(f"  Train: {len(X_train)}, Test: {len(X_test)}")

    # 5) Class balancing
    sample_weights = prepare_balance_weights(y_train, args)

    # 6) Build model
    n_features = X_all.shape[-1]
    model = build_hybrid_lr(args.model, args.window_size, n_features)
    model.summary()
    print()

    # 7) Train
    fit_model(model, X_train, y_train, X_test, y_test, sample_weights, args)

    # 8) Evaluate Model Performance
    evaluate_model(model, X_test, y_test, model_name)

    # 9) Export Model
    convert_to_tflite(model, scaler, X_train, args)


def main():
    parser = argparse.ArgumentParser(description="Train CYD sniffer ML model")
    parser.add_argument("--data_dir", required=True,
                        help="Directory with feat_*.csv and labels.csv")
    parser.add_argument("--output_dir", default="./output",
                        help="Output directory")
    parser.add_argument("--model",
                        choices=["nn", "rf", "lstm_lr", "gru_lr", "rnn_lr"],
                        default="nn",
                        help="Model type: nn (dense), rf (random forest baseline), "
                             "lstm_lr / gru_lr / rnn_lr (hybrid temporal + LR)")
    parser.add_argument("--window_size", type=int, default=10,
                        help="Sliding window size for hybrid models (default: 10)")
    parser.add_argument("--epochs", type=int, default=100,
                        help="Training epochs (nn / hybrid only)")
    parser.add_argument("--batch_size", type=int, default=32,
                        help="Batch size (nn / hybrid only)")
    parser.add_argument(
        "--balance", nargs="*", default=None,
        help="Output heads to balance (default: all). "
             "Options: anomaly, packet_class, protocol, device_type, route_action",
    )
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print("Loading feature data...")
    features = load_features(args.data_dir)

    print("Loading labels...")
    labels = load_labels(args.data_dir)

    if args.model in ("lstm_lr", "gru_lr", "rnn_lr"):
        train_hybrid(features, labels, args)
    else:
        X_train, y_train, X_test, y_test, scaler = prepare_flat_data(features, labels)
        print(f"Model: {args.model}")
        if args.model == "nn":
            train_nn(X_train, y_train, X_test, y_test, scaler, args)
        elif args.model == "rf":
            train_rf(X_train, y_train, X_test, y_test, args)


if __name__ == "__main__":
    main()
