#!/usr/bin/env python3
import argparse
import glob
import os

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

"""
CYD Network Sniffer — Multi-task TFLite Model Training

Reads feature CSVs and labels.csv, trains a multi-task neural network
(anomaly detection, packet classification, protocol ID, device
fingerprinting, routing decision), and exports a quantized int8 TFLite
model + C headers for deployment.

Usage:
    python training/train_model.py --data_dir training/data --output_dir training/output --model nn --balance <feature_cols>

The data_dir should contain:
    - feat_*.csv files from the sniffer
    - labels.csv (generated by generate_labels.py, then reviewed)
"""

# ── Feature columns (must match ESP32 feature_extractor output)

FEATURE_COLS = [
    "pkt_count", "avg_pkt_size", "std_pkt_size", "avg_rssi",
    "pkt_rate", "mgmt_ratio", "data_ratio", "ctrl_ratio",
    "unique_dst_count", "beacon_rate", "probe_req_rate", "retry_ratio",
]

# ── Label definitions

ANOMALY_CLASSES = ["normal", "anomalous"]

PACKET_CLASSES = ["normal", "suspicious", "malicious", "unknown"]

PROTOCOL_CLASSES = [
    "wifi_mgmt", "wifi_data", "wifi_ctrl",
    "dhcp", "dns", "http", "https", "mqtt", "unknown",
]

DEVICE_CLASSES = [
    "router", "phone", "laptop", "iot_sensor", "smart_home",
    "camera", "printer", "game_console", "unknown",
]

ROUTE_ACTIONS = ["allow", "throttle", "block"]


def load_features(data_dir: str) -> pd.DataFrame:
    pattern = os.path.join(data_dir, "feat_*.csv")
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f"No feature files found matching {pattern}")

    dfs = []
    for f in files:
        df = pd.read_csv(f)
        dfs.append(df)
        print(f"  Loaded {f}: {len(df)} rows")

    combined = pd.concat(dfs, ignore_index=True)
    print(f"Total feature rows: {len(combined)}")
    return combined


def load_labels(data_dir: str) -> pd.DataFrame:
    path = os.path.join(data_dir, "labels.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Labels file not found: {path}\n"
            f"Run generate_labels.py first to create it."
        )
    return pd.read_csv(path)


def merge_data(features: pd.DataFrame, labels: pd.DataFrame) -> pd.DataFrame:
    merged = features.merge(labels, on="src_mac", how="inner")
    print(f"Merged rows (labeled): {len(merged)}")
    if len(merged) == 0:
        raise ValueError(
            "No matching MACs between features and labels. "
            "Check that labels.csv src_mac values match the captured data."
        )
    return merged


def build_model(n_features: int):
    inputs = tf.keras.Input(shape=(n_features,), name="features")

    x = tf.keras.layers.Dense(64, activation="relu")(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    x = tf.keras.layers.Dense(32, activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    shared = tf.keras.layers.Dropout(0.2)(x)

    anomaly_out = tf.keras.layers.Dense(
        len(ANOMALY_CLASSES), activation="softmax", name="anomaly"
    )(shared)

    packet_out = tf.keras.layers.Dense(
        len(PACKET_CLASSES), activation="softmax", name="packet_class"
    )(shared)

    protocol_out = tf.keras.layers.Dense(
        len(PROTOCOL_CLASSES), activation="softmax", name="protocol"
    )(shared)

    device_out = tf.keras.layers.Dense(
        len(DEVICE_CLASSES), activation="softmax", name="device_type"
    )(shared)

    route_out = tf.keras.layers.Dense(
        len(ROUTE_ACTIONS), activation="softmax", name="route_action"
    )(shared)

    model = tf.keras.Model(
        inputs=inputs,
        outputs=[anomaly_out, packet_out, protocol_out, device_out, route_out],
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss={
            "anomaly": "sparse_categorical_crossentropy",
            "packet_class": "sparse_categorical_crossentropy",
            "protocol": "sparse_categorical_crossentropy",
            "device_type": "sparse_categorical_crossentropy",
            "route_action": "sparse_categorical_crossentropy",
        },
        metrics={
            "anomaly": ["accuracy"],
            "packet_class": ["accuracy"],
            "protocol": ["accuracy"],
            "device_type": ["accuracy"],
            "route_action": ["accuracy"],
        },
    )

    return model


def encode_labels(df: pd.DataFrame):
    encoders = {}
    label_map = {
        "anomaly": ANOMALY_CLASSES,
        "packet_class": PACKET_CLASSES,
        "protocol": PROTOCOL_CLASSES,
        "device_type": DEVICE_CLASSES,
        "route_action": ROUTE_ACTIONS,
    }

    for col, classes in label_map.items():
        le = LabelEncoder()
        le.fit(classes)
        df[col + "_enc"] = le.transform(df[col].fillna("unknown").str.lower())
        encoders[col] = le

    return df, encoders


def convert_to_tflite(model, scaler, output_dir: str, X_cal=None):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    if X_cal is not None:
        def representative_dataset():
            for i in range(min(200, len(X_cal))):
                yield [X_cal[i:i+1].astype(np.float32)]
        converter.representative_dataset = representative_dataset
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    tflite_path = os.path.join(output_dir, "sniffer_model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)
    print(f"TFLite model saved: {tflite_path} ({len(tflite_model)} bytes)")

    header_path = os.path.join(output_dir, "sniffer_model.h")
    with open(header_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"const unsigned int SNIFFER_MODEL_LEN = {len(tflite_model)};\n")
        f.write("alignas(8) const unsigned char SNIFFER_MODEL[] = {\n")
        for i, byte in enumerate(tflite_model):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{byte:02x},")
            if i % 16 == 15:
                f.write("\n")
        f.write("\n};\n")
    print(f"C header saved: {header_path}")

    scaler_path = os.path.join(output_dir, "scaler_params.h")
    with open(scaler_path, "w") as f:
        f.write("#pragma once\n\n")
        f.write(f"static const int N_FEATURES = {len(FEATURE_COLS)};\n\n")
        f.write("static const float FEATURE_MEAN[] = {\n    ")
        f.write(", ".join(f"{v:.6f}f" for v in scaler.mean_))
        f.write("\n};\n\n")
        f.write("static const float FEATURE_SCALE[] = {\n    ")
        f.write(", ".join(f"{v:.6f}f" for v in scaler.scale_))
        f.write("\n};\n")
    print(f"Scaler params saved: {scaler_path}")


def train_nn(X_train, y_train, X_test, y_test, output_names, scaler, args):
    balance_heads = set(args.balance) if args.balance is not None else set(output_names)
    print(f"  Balancing: {', '.join(sorted(balance_heads))}")

    sample_weights = []
    for i, name in enumerate(output_names):
        labels_arr = y_train[i]
        if name in balance_heads:
            classes = np.unique(labels_arr)
            weights = compute_class_weight("balanced", classes=classes, y=labels_arr)
            weight_map = dict(zip(classes.astype(int), weights))
            sw = np.array([weight_map[int(c)] for c in labels_arr])
            print(f"  {name} class weights: {weight_map}")
        else:
            sw = np.ones(len(labels_arr))
            print(f"  {name}: uniform (not balanced)")
        sample_weights.append(sw)

    print("\nBuilding model...")
    model = build_model(len(FEATURE_COLS))
    model.summary()

    print("\nTraining...")
    model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=args.epochs,
        batch_size=args.batch_size,
        sample_weight=sample_weights,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                patience=15, restore_best_weights=True
            ),
            tf.keras.callbacks.ReduceLROnPlateau(
                factor=0.5, patience=5, min_lr=1e-6
            ),
        ],
        verbose=1,
    )

    print("\nEvaluation:")
    results = model.evaluate(X_test, y_test, verbose=0)
    metric_names = model.metrics_names
    for name, val in zip(metric_names, results):
        print(f"  {name}: {val:.4f}")

    print("\nExporting model...")
    convert_to_tflite(model, scaler, args.output_dir, X_train)

    mapping_path = os.path.join(args.output_dir, "label_mappings.h")
    with open(mapping_path, "w") as f:
        f.write("#pragma once\n\n")
        for task, classes in [
            ("ANOMALY", ANOMALY_CLASSES),
            ("PACKET_CLASS", PACKET_CLASSES),
            ("PROTOCOL", PROTOCOL_CLASSES),
            ("DEVICE_TYPE", DEVICE_CLASSES),
            ("ROUTE_ACTION", ROUTE_ACTIONS),
        ]:
            f.write(f"static const char* const {task}_LABELS[] = {{\n")
            f.write("    " + ", ".join(f'"{c}"' for c in classes))
            f.write(f"\n}};\n")
            f.write(f"static const int {task}_COUNT = {len(classes)};\n\n")
    print(f"Label mappings saved: {mapping_path}")

    print("\nDone! Copy these files to sniffer/src/ for deployment:")
    print(f"  {args.output_dir}/sniffer_model.h")
    print(f"  {args.output_dir}/scaler_params.h")
    print(f"  {args.output_dir}/label_mappings.h")


def train_rf(X_train, y_train, X_test, y_test, output_names, args):
    label_classes = {
        "anomaly": ANOMALY_CLASSES,
        "packet_class": PACKET_CLASSES,
        "protocol": PROTOCOL_CLASSES,
        "device_type": DEVICE_CLASSES,
        "route_action": ROUTE_ACTIONS,
    }

    balance_heads = set(args.balance) if args.balance is not None else set(output_names)

    print(f"\n{'='*60}")
    print("Random Forest Baseline — one classifier per output head")
    print(f"{'='*60}")

    for i, name in enumerate(output_names):
        class_weight = "balanced" if name in balance_heads else None
        rf = RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            class_weight=class_weight,
            random_state=42,
            n_jobs=-1,
        )
        rf.fit(X_train, y_train[i])

        y_pred = rf.predict(X_test[i] if isinstance(X_test, list) else X_test)
        acc = accuracy_score(y_test[i], y_pred)

        classes_present = np.unique(np.concatenate([y_test[i], y_pred]))
        class_names = label_classes[name]
        target_names = [class_names[int(c)] for c in classes_present]

        print(f"\n--- {name} (accuracy: {acc:.4f}, balanced: {class_weight is not None}) ---")
        print(classification_report(
            y_test[i], y_pred,
            labels=classes_present,
            target_names=target_names,
            zero_division=0,
        ))

        importances = rf.feature_importances_
        ranked = sorted(zip(FEATURE_COLS, importances), key=lambda x: -x[1])
        print(f"  Top features: ", end="")
        print(", ".join(f"{name}={imp:.3f}" for name, imp in ranked[:5]))


def main():
    parser = argparse.ArgumentParser(description="Train CYD sniffer ML model")
    parser.add_argument("--data_dir", required=True, help="Directory with feat_*.csv and labels.csv")
    parser.add_argument("--output_dir", default="./output", help="Output directory")
    parser.add_argument("--model", choices=["nn", "rf"], default="nn",
                        help="Model type: nn (neural network) or rf (random forest baseline)")
    parser.add_argument("--epochs", type=int, default=100, help="Training epochs (nn only)")
    parser.add_argument("--batch_size", type=int, default=32, help="Batch size (nn only)")
    parser.add_argument(
        "--balance", nargs="*", default=None,
        help="Output heads to balance (default: all). "
             "Options: anomaly, packet_class, protocol, device_type, route_action",
    )
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print("Loading feature data...")
    features = load_features(args.data_dir)

    print("Loading labels...")
    labels = load_labels(args.data_dir)

    print("Merging data...")
    df = merge_data(features, labels)

    print("Encoding labels...")
    df, encoders = encode_labels(df)

    X = df[FEATURE_COLS].values.astype(np.float32)
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    output_names = ["anomaly", "packet_class", "protocol", "device_type", "route_action"]
    enc_cols = [n + "_enc" for n in output_names]
    y_all = [df[c].values for c in enc_cols]

    indices = np.arange(len(X))
    train_idx, test_idx = train_test_split(indices, test_size=0.2, random_state=42)

    X_train, X_test = X[train_idx], X[test_idx]
    y_train = [v[train_idx] for v in y_all]
    y_test = [v[test_idx] for v in y_all]

    print(f"\nTrain: {len(X_train)}, Test: {len(X_test)}")
    print(f"Features: {len(FEATURE_COLS)}")
    print(f"Model: {args.model}")

    if args.model == "nn":
        train_nn(X_train, y_train, X_test, y_test, output_names, scaler, args)
    elif args.model == "rf":
        train_rf(X_train, y_train, X_test, y_test, output_names, args)


if __name__ == "__main__":
    main()
