#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from training.labels import DEVICE_CLASSES, OUI_DEVICE_MAP

"""
Generate src/oui_table.h from training.labels.OUI_DEVICE_MAP and
training/data/oui_cache.json.

Each row pairs a 24-bit OUI with its device_type index (matching
DEVICE_TYPE_LABELS in src/label_mappings.h). At runtime, oui_lookup() does
a binary search over the sorted array to classify a device from its MAC.

The OUI_DEVICE_MAP in training/labels.py is the source of truth — to skip a
vendor on-device, remove it from the map rather than special-casing here.

Default behaviour is INCREMENTAL: if src/oui_table.h already exists, its
entries are parsed and preserved (including any hand-edited rows), and only
OUIs from the cache that aren't already in the table are appended. Pass
--regenerate to discard the existing file and rebuild from scratch.

Usage:
    python tools/generate_oui_table.py              # incremental merge
    python tools/generate_oui_table.py --regenerate # full rebuild
    (or `make oui-table`)

Output:
    src/oui_table.h
"""

DEVICE_INDEX = {name: i for i, name in enumerate(DEVICE_CLASSES)}
INDEX_DEVICE = {i: name for name, i in DEVICE_INDEX.items()}

# Matches lines like:  {0xABCDEF, 9}, // dtype        Vendor Name
OUI_LINE_RE = re.compile(
    r"\{\s*0x([0-9A-Fa-f]{6})\s*,\s*(\d+)\s*\}\s*,\s*//\s*(\S+)\s+(.*?)\s*$"
)


def parse_existing(path: str):
    """Read an existing oui_table.h and return {oui_int: (oui, idx, vendor, dtype)}.

    Returns an empty dict if the file is missing. Lines that don't match the
    expected row format are skipped silently (preamble, struct, etc.).
    """
    if not os.path.exists(path):
        return {}
    existing = {}
    with open(path) as f:
        for line in f:
            m = OUI_LINE_RE.search(line)
            if not m:
                continue
            oui = int(m.group(1), 16)
            idx = int(m.group(2))
            dtype = m.group(3)
            vendor = m.group(4).rstrip(",").strip()
            existing[oui] = (oui, idx, vendor, dtype)
    return existing


def classify_vendor(vendor: str):
    v = vendor.lower()
    for keyword, dtype in OUI_DEVICE_MAP.items():
        if keyword.lower() in v:
            return dtype
    return None


def parse_oui(prefix: str):
    p = prefix.replace(":", "").replace("-", "").strip().upper()
    if len(p) < 6:
        return None
    try:
        return int(p[:6], 16)
    except ValueError:
        return None


def build_entries(oui_cache: dict, existing: dict | None = None):
    """Build the entry list from cache, skipping OUIs already in `existing`.

    Returns (merged_entries, added_count, skipped_count). `existing` rows are
    preserved verbatim (their stored device_type index wins over whatever the
    keyword classifier would emit).
    """
    existing = existing or {}
    new_entries = []
    skipped = 0
    for prefix, vendor in oui_cache.items():
        oui = parse_oui(prefix)
        if oui is None:
            continue
        if oui in existing:
            # Already on-device — leave it alone (preserves hand-edits).
            continue
        dtype = classify_vendor(vendor)
        if dtype is None or dtype not in DEVICE_INDEX:
            skipped += 1
            continue
        new_entries.append((oui, DEVICE_INDEX[dtype], vendor, dtype))

    # Dedup new entries by OUI (cache should already be unique, belt-and-braces).
    seen = set()
    deduped_new = []
    for e in new_entries:
        if e[0] in seen:
            continue
        seen.add(e[0])
        deduped_new.append(e)

    merged = list(existing.values()) + deduped_new
    merged.sort(key=lambda e: e[0])
    return merged, len(deduped_new), skipped


HEADER_PREAMBLE = """\
// Generated by tools/generate_oui_table.py — DO NOT EDIT.
// Sorted by 24-bit OUI; oui_lookup() does a binary search.

#pragma once

#include <cstdint>

struct OuiEntry {
    uint32_t oui;          // 24-bit OUI in high three bytes of mac
    uint8_t  device_type;  // index into DEVICE_TYPE_LABELS
};

"""


def emit_header(entries, path: str):
    lines = [HEADER_PREAMBLE]
    lines.append(f"static constexpr int OUI_TABLE_LEN = {len(entries)};\n\n")
    if entries:
        lines.append("static constexpr OuiEntry OUI_TABLE[] = {\n")
        for oui, idx, vendor, dtype in entries:
            safe_vendor = vendor.replace("/", "_").replace("\n", " ")
            lines.append(f"    {{0x{oui:06X}, {idx}}}, // {dtype:<12} {safe_vendor}\n")
        lines.append("};\n")
    else:
        # Keep a one-element array so OUI_TABLE[0] is valid; LEN=0 guards lookup.
        lines.append("static constexpr OuiEntry OUI_TABLE[] = { {0, 0} };\n")
    with open(path, "w") as f:
        f.writelines(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default="training/data/oui_cache.json")
    ap.add_argument("--out", default="src/oui_table.h")
    ap.add_argument(
        "--regenerate",
        action="store_true",
        help="Discard the existing oui_table.h and rebuild from cache only. "
             "Default is incremental: preserve existing entries and only append new ones.",
    )
    args = ap.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    cache_path = args.cache if os.path.isabs(args.cache) else os.path.join(repo_root, args.cache)
    if os.path.exists(cache_path):
        with open(cache_path) as f:
            oui_cache = json.load(f)
        print(f"Loaded {len(oui_cache)} OUIs from {cache_path}")
    else:
        oui_cache = {}
        print(f"No OUI cache at {cache_path}; emitting empty table")

    out_path = args.out if os.path.isabs(args.out) else os.path.join(repo_root, args.out)

    if args.regenerate:
        existing = {}
        if os.path.exists(out_path):
            print(f"--regenerate: discarding existing entries in {out_path}")
    else:
        existing = parse_existing(out_path)
        if existing:
            print(f"Loaded {len(existing)} existing entries from {out_path} (preserving)")
        else:
            print(f"No existing {out_path}; generating from scratch")

    entries, added, skipped = build_entries(oui_cache, existing)
    emit_header(entries, out_path)
    print(
        f"Wrote {len(entries)} entries to {out_path} "
        f"(added {added}, preserved {len(existing)}, skipped {skipped} unmapped)"
    )


if __name__ == "__main__":
    main()
