// Generated by tools/generate_oui_table.py — DO NOT EDIT.
// Sorted by 24-bit OUI; oui_lookup() does a binary search.

#pragma once

#include <cstdint>

struct OuiEntry {
    uint32_t oui;          // 24-bit OUI in high three bytes of mac
    uint8_t  device_type;  // index into DEVICE_TYPE_LABELS
};

static constexpr int OUI_TABLE_LEN = 86;

static constexpr OuiEntry OUI_TABLE[] = {
    {0x000E58, 4}, // smart_home   Sonos, Inc.
    {0x002000, 6}, // printer      LEXMARK INTERNATIONAL, INC.
    {0x002DB3, 4}, // smart_home   AMPAK Technology,Inc.
    {0x00904C, 0}, // router       Epigram, Inc.
    {0x00E63A, 0}, // router       Ruckus Wireless
    {0x00F48D, 9}, // flock        Liteon Technology Corporation
    {0x0C298F, 3}, // iot_sensor   Tesla, Inc.
    {0x100C6B, 0}, // router       NETGEAR
    {0x102CB1, 4}, // smart_home   Smart Innovation LLC
    {0x10DA43, 0}, // router       NETGEAR
    {0x10E177, 0}, // router       Commscope
    {0x145AFC, 9}, // flock        Liteon Technology Corporation
    {0x186041, 0}, // router       Arcadyan Corporation
    {0x18B430, 4}, // smart_home   Nest Labs Inc.
    {0x1C9ECC, 0}, // router       Vantiva USA LLC
    {0x2441FE, 0}, // router       WNC Corporation
    {0x24B2B9, 9}, // flock        Liteon Technology Corporation
    {0x24D7EB, 4}, // smart_home   Espressif Inc.
    {0x341343, 4}, // smart_home   GE Lighting
    {0x381F8D, 4}, // smart_home   Tuya Smart Inc.
    {0x3C3174, 1}, // phone        Google, Inc.
    {0x3C9180, 9}, // flock        Liteon Technology Corporation
    {0x3C9BD6, 4}, // smart_home   Vizio, Inc
    {0x400FC1, 0}, // router       Vantiva USA LLC
    {0x409F38, 2}, // cpu          AzureWave Technology Inc.
    {0x446132, 4}, // smart_home   ecobee inc
    {0x44A3BB, 2}, // cpu          Intel Corporate
    {0x4831B7, 4}, // smart_home   Espressif Inc.
    {0x48A6B8, 4}, // smart_home   Sonos, Inc.
    {0x4CB9EA, 4}, // smart_home   iRobot Corporation
    {0x4CFCAA, 3}, // iot_sensor   Tesla,Inc.
    {0x501479, 4}, // smart_home   iRobot Corporation
    {0x54077D, 0}, // router       NETGEAR
    {0x5800E3, 9}, // flock        Liteon Technology Corporation
    {0x589630, 0}, // router       Vantiva USA LLC
    {0x5C93A2, 9}, // flock        Liteon Technology Corporation
    {0x60CF84, 2}, // cpu          ASUSTek COMPUTER INC.
    {0x641666, 4}, // smart_home   Nest Labs Inc.
    {0x646E69, 9}, // flock        Liteon Technology Corporation
    {0x649A63, 4}, // smart_home   Ring LLC
    {0x64E833, 4}, // smart_home   Espressif Inc.
    {0x683A48, 4}, // smart_home   SAMJIN Co., Ltd.
    {0x6CCDD6, 0}, // router       NETGEAR
    {0x700894, 9}, // flock        Liteon Technology Corporation
    {0x704A0E, 4}, // smart_home   AMPAK Technology,Inc.
    {0x707DA1, 0}, // router       Sagemcom Broadband SAS
    {0x70C94E, 9}, // flock        Liteon Technology Corporation
    {0x744CA1, 9}, // flock        Liteon Technology Corporation
    {0x74AB93, 4}, // smart_home   Blink by Amazon
    {0x74FECE, 0}, // router       TP-Link Systems Inc
    {0x78D294, 0}, // router       NETGEAR
    {0x803049, 9}, // flock        Liteon Technology Corporation
    {0x804AF2, 4}, // smart_home   Sonos, Inc.
    {0x80953A, 2}, // cpu          Apple, Inc.
    {0x80BC37, 0}, // router       Ruckus Wireless
    {0x8C5A25, 0}, // router       Commscope
    {0x8C79F5, 1}, // phone        Samsung Electronics Co.,Ltd
    {0x90CAFA, 1}, // phone        Google, Inc.
    {0x940853, 9}, // flock        Liteon Technology Corporation
    {0x941865, 0}, // router       NETGEAR
    {0x946A77, 0}, // router       Vantiva USA LLC
    {0x9C05D6, 0}, // router       Ubiquiti Inc
    {0x9C2F9D, 9}, // flock        Liteon Technology Corporation
    {0xAC6784, 1}, // phone        Google, Inc.
    {0xAC919B, 0}, // router       WNC Corporation
    {0xB03956, 0}, // router       NETGEAR
    {0xB06A41, 1}, // phone        Google, Inc.
    {0xB07FB9, 0}, // router       NETGEAR
    {0xB4636F, 1}, // phone        Nokia Solutions and Networks GmbH & Co. KG
    {0xB81EA4, 9}, // flock        Liteon Technology Corporation
    {0xBCDF58, 1}, // phone        Google, Inc.
    {0xC03532, 9}, // flock        Liteon Technology Corporation
    {0xCC8826, 1}, // phone        LG Innotek
    {0xD03957, 9}, // flock        Liteon Technology Corporation
    {0xD4F547, 1}, // phone        Google, Inc.
    {0xD8F3BC, 9}, // flock        Liteon Tech Corporation
    {0xE0C250, 0}, // router       NETGEAR
    {0xE4AAEA, 9}, // flock        Liteon Technology Corporation
    {0xE8D0FC, 9}, // flock        Liteon Technology Corporation
    {0xECA81F, 0}, // router       Vantiva USA LLC
    {0xF0704F, 1}, // phone        Samsung Electronics Co.,Ltd
    {0xF46ADD, 9}, // flock        Liteon Technology Corporation
    {0xF85128, 4}, // smart_home   SimpliSafe
    {0xF855CD, 3}, // iot_sensor   Visteon Corporation
    {0xF8A2D6, 9}, // flock        Liteon Technology Corporation
    {0xF8F532, 0}, // router       Commscope
};
